(load-file "characters (A-M).el")
(load-file "characters (N-Z).el")
(load-file "quotes.el")
(load-file "trigram.el")

(defun character ()
  "Generating function: writes a function for inserting some given character."
  (interactive)
  (let (name char desc)
    (setq name (read-string "Enter the name for the new function: "))
    (setq char (read-string "Enter the character: "))
    (setq desc (string-replace "-" " " name))
    (insert (concat "(defun " name " ()\n  \"Inserts a " desc " character.\"\n  (interactive)\n  (insert \"" char "\"))\n; (describe-function '" name ")\n"))
    )
  )
					; (describe-function 'character)
