
(defun Arabic-pair-2-base-100 (ch)
  "Returns the base-100 digit corresponding to the pair of Western Arabic digits in CH."
  (cond
    ((string= ch "00") "~")
    ((string= ch "01") "a")
    ((string= ch "02") "b")
    ((string= ch "03") "c")
    ((string= ch "04") "d")
    ((string= ch "05") "e")
    ((string= ch "06") "f")
    ((string= ch "07") "g")
    ((string= ch "08") "h")
    ((string= ch "09") "i")
    ((string= ch "10") "j")
    ((string= ch "11") "k")
    ((string= ch "12") "l")
    ((string= ch "13") "m")
    ((string= ch "14") "n")
    ((string= ch "15") "o")
    ((string= ch "16") "p")
    ((string= ch "17") "q")
    ((string= ch "18") "r")
    ((string= ch "19") "s")
    ((string= ch "20") "t")
    ((string= ch "21") "u")
    ((string= ch "22") "v")
    ((string= ch "23") "w")
    ((string= ch "24") "x")
    ((string= ch "25") "y")
    ((string= ch "26") "z")
    ((string= ch "27") "/")
    ((string= ch "28") ":")
    ((string= ch "29") "\\")
    ((string= ch "30") "0")
    ((string= ch "31") "1")
    ((string= ch "32") "2")
    ((string= ch "33") "3")
    ((string= ch "34") "4")
    ((string= ch "35") "5")
    ((string= ch "36") "6")
    ((string= ch "37") "7")
    ((string= ch "38") "8")
    ((string= ch "39") "9")
    ((string= ch "40") "=")
    ((string= ch "41") "α")
    ((string= ch "42") "β")
    ((string= ch "43") "γ")
    ((string= ch "44") "δ")
    ((string= ch "45") "ε")
    ((string= ch "46") "ζ")
    ((string= ch "47") "η")
    ((string= ch "48") "θ")
    ((string= ch "49") "ι")
    ((string= ch "50") "κ")
    ((string= ch "51") "λ")
    ((string= ch "52") "μ")
    ((string= ch "53") "ν")
    ((string= ch "54") "ξ")
    ((string= ch "55") "+")
    ((string= ch "56") "π")
    ((string= ch "57") "ρ")
    ((string= ch "58") "σ")
    ((string= ch "59") "τ")
    ((string= ch "60") "υ")
    ((string= ch "61") "ϕ")
    ((string= ch "62") "χ")
    ((string= ch "63") "ψ")
    ((string= ch "64") "ω")
    ((string= ch "65") "A")
    ((string= ch "66") "B")
    ((string= ch "67") "C")
    ((string= ch "68") "D")
    ((string= ch "69") "E")
    ((string= ch "70") "F")
    ((string= ch "71") "G")
    ((string= ch "72") "H")
    ((string= ch "73") "I")
    ((string= ch "74") "J")
    ((string= ch "75") "K")
    ((string= ch "76") "L")
    ((string= ch "77") "M")
    ((string= ch "78") "N")
    ((string= ch "79") "O")
    ((string= ch "80") "P")
    ((string= ch "81") "Q")
    ((string= ch "82") "R")
    ((string= ch "83") "S")
    ((string= ch "84") "T")
    ((string= ch "85") "U")
    ((string= ch "86") "V")
    ((string= ch "87") "W")
    ((string= ch "88") "X")
    ((string= ch "89") "Y")
    ((string= ch "90") "Z")
    ((string= ch "91") "!")
    ((string= ch "92") "@")
    ((string= ch "93") "#")
    ((string= ch "94") "$")
    ((string= ch "95") "%")
    ((string= ch "96") "^")
    ((string= ch "97") "&")
    ((string= ch "98") "*")
    ((string= ch "99") "?")
    (t "")))
					; (describe-function 'Arabic-pair-2-char)

(defun base-100-2-Arabic-pair (char$)
  "Returns the pair of Western Arabic digits corresponding to the base-100 digit."
  (cond
    ((string= char$ "~") "00")
    ((string= char$ "a") "01")
    ((string= char$ "b") "02")
    ((string= char$ "c") "03")
    ((string= char$ "d") "04")
    ((string= char$ "e") "05")
    ((string= char$ "f") "06")
    ((string= char$ "g") "07")
    ((string= char$ "h") "08")
    ((string= char$ "i") "09")
    ((string= char$ "j") "10")
    ((string= char$ "k") "11")
    ((string= char$ "l") "12")
    ((string= char$ "m") "13")
    ((string= char$ "n") "14")
    ((string= char$ "o") "15")
    ((string= char$ "p") "16")
    ((string= char$ "q") "17")
    ((string= char$ "r") "18")
    ((string= char$ "s") "19")
    ((string= char$ "t") "20")
    ((string= char$ "u") "21")
    ((string= char$ "v") "22")
    ((string= char$ "w") "23")
    ((string= char$ "x") "24")
    ((string= char$ "y") "25")
    ((string= char$ "z") "26")
    ((string= char$ "/") "27")
    ((string= char$ ":") "28")
    ((string= char$ "\\") "29")
    ((string= char$ "0") "30")
    ((string= char$ "1") "31")
    ((string= char$ "2") "32")
    ((string= char$ "3") "33")
    ((string= char$ "4") "34")
    ((string= char$ "5") "35")
    ((string= char$ "6") "36")
    ((string= char$ "7") "37")
    ((string= char$ "8") "38")
    ((string= char$ "9") "39")
    ((string= char$ "=") "40")
    ((string= char$ "α") "41")
    ((string= char$ "β") "42")
    ((string= char$ "γ") "43")
    ((string= char$ "δ") "44")
    ((string= char$ "ε") "45")
    ((string= char$ "ζ") "46")
    ((string= char$ "η") "47")
    ((string= char$ "θ") "48")
    ((string= char$ "ι") "49")
    ((string= char$ "κ") "50")
    ((string= char$ "λ") "51")
    ((string= char$ "μ") "52")
    ((string= char$ "ν") "53")
    ((string= char$ "ξ") "54")
    ((string= char$ "+") "55")
    ((string= char$ "π") "56")
    ((string= char$ "ρ") "57")
    ((string= char$ "σ") "58")
    ((string= char$ "τ") "59")
    ((string= char$ "υ") "60")
    ((string= char$ "ϕ") "61")
    ((string= char$ "χ") "62")
    ((string= char$ "ψ") "63")
    ((string= char$ "ω") "64")
    ((string= char$ "A") "65")
    ((string= char$ "B") "66")
    ((string= char$ "C") "67")
    ((string= char$ "D") "68")
    ((string= char$ "E") "69")
    ((string= char$ "F") "70")
    ((string= char$ "G") "71")
    ((string= char$ "H") "72")
    ((string= char$ "I") "73")
    ((string= char$ "J") "74")
    ((string= char$ "K") "75")
    ((string= char$ "L") "76")
    ((string= char$ "M") "77")
    ((string= char$ "N") "78")
    ((string= char$ "O") "79")
    ((string= char$ "P") "80")
    ((string= char$ "Q") "81")
    ((string= char$ "R") "82")
    ((string= char$ "S") "83")
    ((string= char$ "T") "84")
    ((string= char$ "U") "85")
    ((string= char$ "V") "86")
    ((string= char$ "W") "87")
    ((string= char$ "X") "88")
    ((string= char$ "Y") "89")
    ((string= char$ "Z") "90")
    ((string= char$ "!") "91")
    ((string= char$ "@") "92")
    ((string= char$ "#") "93")
    ((string= char$ "$") "94")
    ((string= char$ "%") "95")
    ((string= char$ "^") "96")
    ((string= char$ "&") "97")
    ((string= char$ "*") "98")
    ((string= char$ "?") "99")
    (t "")))
; (describe-function 'base-100-2-Arabic-pair)

(defun is-even (n)
  "Returns t if N is an even integer and nil if N is an odd integer."
  (= (- (/ n 2.0) (/ n 2)) 0.0))
					; (describe-function 'is-even)

(defun char-trans-Arabic-pair-2-base-100-1 (st)
  "Given string ST of Western Arabic digits, prints out the corresponding encoded string of base-100 characters."
  (let (digit-pair)
    (if (not (is-even (length st)))
      (setq st (concat "0" st)))
    (while (> (length st) 0)
      (setq digit-pair (substring st 0 2))
      (insert (Arabic-pair-2-base-100 digit-pair))
      (setq st (substring st 2 (length st))))))
					; (describe-function 'char-trans-Arabic-pair-1)

(defun number-2-base-100-1 ()
  "Converts a Western Arabic natural number to a base-100 numeral."  
  (interactive)
  (let (num-ST)
    (setq num-ST (read-string "Enter a number (positive integer): "))
    (char-trans-Arabic-pair-2-base-100-1 num-ST)
  )
)
  
(defun Arabic-pair-2-chemical (ch)
  "Returns the chemical element symbol corresponding to the pair of Western Arabic digits given in CH."
  (cond
    ((string= ch "00") "Fm")
    ((string= ch "01") "H")
    ((string= ch "02") "He")
    ((string= ch "03") "Li")
    ((string= ch "04") "Be")
    ((string= ch "05") "B")
    ((string= ch "06") "C")
    ((string= ch "07") "N")
    ((string= ch "08") "O")
    ((string= ch "09") "F")
    ((string= ch "10") "Ne")
    ((string= ch "11") "Na")
    ((string= ch "12") "Mg")
    ((string= ch "13") "Al")
    ((string= ch "14") "Si")
    ((string= ch "15") "P")
    ((string= ch "16") "S")
    ((string= ch "17") "Cl")
    ((string= ch "18") "Ar")
    ((string= ch "19") "K")
    ((string= ch "20") "Ca")
    ((string= ch "21") "Sc")
    ((string= ch "22") "Ti")
    ((string= ch "23") "V")
    ((string= ch "24") "Cr")
    ((string= ch "25") "Mn")
    ((string= ch "26") "Fe")
    ((string= ch "27") "Co")
    ((string= ch "28") "Ni")
    ((string= ch "29") "Cu")
    ((string= ch "30") "Zn")
    ((string= ch "31") "Ga")
    ((string= ch "32") "Ge")
    ((string= ch "33") "As")
    ((string= ch "34") "Se")
    ((string= ch "35") "Br")
    ((string= ch "36") "Kr")
    ((string= ch "37") "Rb")
    ((string= ch "38") "Sr")
    ((string= ch "39") "Y")
    ((string= ch "40") "Zr")
    ((string= ch "41") "Nb")
    ((string= ch "42") "Mo")
    ((string= ch "43") "Tc")
    ((string= ch "44") "Ru")
    ((string= ch "45") "Rh")
    ((string= ch "46") "Pd")
    ((string= ch "47") "Ag")
    ((string= ch "48") "Cd")
    ((string= ch "49") "In")
    ((string= ch "50") "Sn")
    ((string= ch "51") "Sb")
    ((string= ch "52") "Te")
    ((string= ch "53") "I")
    ((string= ch "54") "Xe")
    ((string= ch "55") "Cs")
    ((string= ch "56") "Ba")
    ((string= ch "57") "La")
    ((string= ch "58") "Ce")
    ((string= ch "59") "Pr")
    ((string= ch "60") "Nd")
    ((string= ch "61") "Pm")
    ((string= ch "62") "Sm")
    ((string= ch "63") "Eu")
    ((string= ch "64") "Gd")
    ((string= ch "65") "Tb")
    ((string= ch "66") "Dy")
    ((string= ch "67") "Ho")
    ((string= ch "68") "Er")
    ((string= ch "69") "Tm")
    ((string= ch "70") "Yb")
    ((string= ch "71") "Lu")
    ((string= ch "72") "Hf")
    ((string= ch "73") "Ta")
    ((string= ch "74") "W")
    ((string= ch "75") "Re")
    ((string= ch "76") "Os")
    ((string= ch "77") "Ir")
    ((string= ch "78") "Pt")
    ((string= ch "79") "Au")
    ((string= ch "80") "Hg")
    ((string= ch "81") "Tl")
    ((string= ch "82") "Pb")
    ((string= ch "83") "Bi")
    ((string= ch "84") "Po")
    ((string= ch "85") "At")
    ((string= ch "86") "Rn")
    ((string= ch "87") "Fr")
    ((string= ch "88") "Ra")
    ((string= ch "89") "Ac")
    ((string= ch "90") "Th")
    ((string= ch "91") "Pa")
    ((string= ch "92") "U")
    ((string= ch "93") "Np")
    ((string= ch "94") "Pu")
    ((string= ch "95") "Am")
    ((string= ch "96") "Cm")
    ((string= ch "97") "Bk")
    ((string= ch "98") "Cf")
    ((string= ch "99") "Es")
    (t "")))
					; (describe-function 'Arabic-pair-2-chemical)

(defun char-trans-Arabic-pair-2-chemical-1 (st)
  "Given string ST of Western Arabic digits, prints out the corresponding encoding as a string of chemical element symbols."
  (let (digit-pair)
    (if (is-even (length st))
      (while (> (length st) 0)
        (setq digit-pair (substring st 0 2))
        (insert (Arabic-pair-2-chemical digit-pair))
        (setq st (substring st 2 (length st))))
      (y-or-n-p "Error: the length of argument ST has to be even."))))
					; (describe-function 'char-trans-Arabic-pair-1)

(defun number-2-chemical-1 ()
  "Converts a Western Arabic natural number to a string of chemical element symbols."
  (interactive)
  (let (num-ST)
    (setq num-ST (read-string "Enter a number (positive integer): "))
    (char-trans-Arabic-pair-2-chemical-1 num-ST)))
; (describe-function 'number-2-chemical-1)

(defun Arabic-pair-2-chemical-padded (ch)
  "Returns the chemical element symbol corresponding to the pair of Western Arabic digits given in CH."
  (cond
    ((string= ch "00") "Fm")
    ((string= ch "01") "H#")
    ((string= ch "02") "He")
    ((string= ch "03") "Li")
    ((string= ch "04") "Be")
    ((string= ch "05") "B#")
    ((string= ch "06") "C#")
    ((string= ch "07") "N#")
    ((string= ch "08") "O#")
    ((string= ch "09") "F#")
    ((string= ch "10") "Ne")
    ((string= ch "11") "Na")
    ((string= ch "12") "Mg")
    ((string= ch "13") "Al")
    ((string= ch "14") "Si")
    ((string= ch "15") "P#")
    ((string= ch "16") "S#")
    ((string= ch "17") "Cl")
    ((string= ch "18") "Ar")
    ((string= ch "19") "K#")
    ((string= ch "20") "Ca")
    ((string= ch "21") "Sc")
    ((string= ch "22") "Ti")
    ((string= ch "23") "V#")
    ((string= ch "24") "Cr")
    ((string= ch "25") "Mn")
    ((string= ch "26") "Fe")
    ((string= ch "27") "Co")
    ((string= ch "28") "Ni")
    ((string= ch "29") "Cu")
    ((string= ch "30") "Zn")
    ((string= ch "31") "Ga")
    ((string= ch "32") "Ge")
    ((string= ch "33") "As")
    ((string= ch "34") "Se")
    ((string= ch "35") "Br")
    ((string= ch "36") "Kr")
    ((string= ch "37") "Rb")
    ((string= ch "38") "Sr")
    ((string= ch "39") "Y#")
    ((string= ch "40") "Zr")
    ((string= ch "41") "Nb")
    ((string= ch "42") "Mo")
    ((string= ch "43") "Tc")
    ((string= ch "44") "Ru")
    ((string= ch "45") "Rh")
    ((string= ch "46") "Pd")
    ((string= ch "47") "Ag")
    ((string= ch "48") "Cd")
    ((string= ch "49") "In")
    ((string= ch "50") "Sn")
    ((string= ch "51") "Sb")
    ((string= ch "52") "Te")
    ((string= ch "53") "I#")
    ((string= ch "54") "Xe")
    ((string= ch "55") "Cs")
    ((string= ch "56") "Ba")
    ((string= ch "57") "La")
    ((string= ch "58") "Ce")
    ((string= ch "59") "Pr")
    ((string= ch "60") "Nd")
    ((string= ch "61") "Pm")
    ((string= ch "62") "Sm")
    ((string= ch "63") "Eu")
    ((string= ch "64") "Gd")
    ((string= ch "65") "Tb")
    ((string= ch "66") "Dy")
    ((string= ch "67") "Ho")
    ((string= ch "68") "Er")
    ((string= ch "69") "Tm")
    ((string= ch "70") "Yb")
    ((string= ch "71") "Lu")
    ((string= ch "72") "Hf")
    ((string= ch "73") "Ta")
    ((string= ch "74") "W#")
    ((string= ch "75") "Re")
    ((string= ch "76") "Os")
    ((string= ch "77") "Ir")
    ((string= ch "78") "Pt")
    ((string= ch "79") "Au")
    ((string= ch "80") "Hg")
    ((string= ch "81") "Tl")
    ((string= ch "82") "Pb")
    ((string= ch "83") "Bi")
    ((string= ch "84") "Po")
    ((string= ch "85") "At")
    ((string= ch "86") "Rn")
    ((string= ch "87") "Fr")
    ((string= ch "88") "Ra")
    ((string= ch "89") "Ac")
    ((string= ch "90") "Th")
    ((string= ch "91") "Pa")
    ((string= ch "92") "U#")
    ((string= ch "93") "Np")
    ((string= ch "94") "Pu")
    ((string= ch "95") "Am")
    ((string= ch "96") "Cm")
    ((string= ch "97") "Bk")
    ((string= ch "98") "Cf")
    ((string= ch "99") "Es")
    (t "")))
					; (describe-function 'Arabic-pair-2-chemical-padded)

(defun char-trans-Arabic-pair-2-chemical-padded-1 (st)
  "Given string ST of Western Arabic digits, prints out the corresponding encoding as a string of chemical element symbols."
  (let (digit-pair)
    (if (is-even (length st))
      (while (> (length st) 0)
        (setq digit-pair (substring st 0 2))
        (insert (Arabic-pair-2-chemical-padded digit-pair))
        (setq st (substring st 2 (length st))))
      (y-or-n-p "Error: the length of argument ST has to be even."))))
					; (describe-function 'char-trans-Arabic-pair-2-chemical-padded-1)

					; (not t)
					; (not nil)

(defun char-trans-Arabic-pair-2-chemical-padded-1 (st)
  "Given string ST of Western Arabic digits, prints out the corresponding encoding as a string of chemical element symbols. Single-letter symbols are padded with an octothorpe."
  (let (digit-pair)
    (if (not (is-even (length st)))
      (setq st (concat "0" st)))
    (while (> (length st) 0)
      (setq digit-pair (substring st 0 2))
      (insert (Arabic-pair-2-chemical-padded digit-pair))
      (setq st (substring st 2 (length st))))))
					; (describe-function 'char-trans-Arabic-pair-2-chemical-padded-1)


(defun number-2-chemical-padded-1 ()
  "Converts a Western Arabic natural number to a string of chemical element symbols."
  (interactive)
  (let (num-ST)
    (setq num-ST (read-string "Enter a number (positive integer): "))
    (char-trans-Arabic-pair-2-chemical-padded-1 num-ST)))
; (describe-function 'number-2-chemical-padded-1)
