(load-file "numerals 2.el")
(load-file "DEBUG.el")
;(load-file "Doomsday Rule.el")

(setq debug-1 nil)

(defun date.stamp ()
  "Date stamp."
  (interactive)
  (insert (format-time-string "%Y.%m.%d")))
; (describe-function 'date-stamp)

(defun Dat.stamp ()
  "Date stamp (using three letters for month)."
  (interactive)
  (insert (format-time-string "%Y.%h.%d")))
					; (describe-function 'Dat-stamp)

(defun DAT.stamp ()
  "Date stamp (using all-cap three letters for month and using hyphen as separator)."
  (interactive)
  (insert (concat (format-time-string "%Y") "-" (upcase (format-time-string "%h")) "-" (format-time-string "%d"))))
; (describe-function 'DAT-stamp)

(defun Dat-stamp ()
  "Date stamp (using three letters for month and using hyphen as separator)."
  (interactive)
  (insert (format-time-string "%Y-%h-%d")))
					; (describe-function 'Dat-stamp-hyphen)

(defun DAT-stamp ()
  "Date stamp (using all-cap three letters for month and using hyphen as separator)."
  (interactive)
  (insert (concat (format-time-string "%Y") "-" (upcase (format-time-string "%h")) "-" (format-time-string "%d"))))
; (describe-function 'DAT-stamp)

(defun DAT-DOTW-stamp ()
  "Like DAT-stamp but with additional space and three-letter all-cap day of the week."
  (interactive)
  (let (string$ year month day DOTW$)
    (setq string$ (concat (format-time-string "%Y") "-" (upcase (format-time-string "%h")) "-" (format-time-string "%d")))
    (setq year (string-to-number (format-time-string "%Y")))
    (setq month (string-to-number (format-time-string "%m")))
    (setq day (string-to-number (format-time-string "%d")))
    (setq DOTW$ (upcase (substring (Doomsday-Rule year month day) 0 3)))
    (setq string$ (concat string$ " " DOTW$))
    (insert string$)))
; (describe-function 'DAT-DOTW-stamp)

(defun DAT-DOTW-stamp ()
  "Like DAT-stamp but with additional space and three-letter all-cap day of the week."
  (interactive)
  (let (string$)
    (setq string$ (concat (format-time-string "%Y") "-" (upcase (format-time-string "%h")) "-" (format-time-string "%d")))
    (setq string$ (concat string$ " " (upcase (format-time-string "%a"))))
    (insert string$)))
; (describe-function 'DAT-DOTW-stamp)

(defun DAT-DOTW-TM-stamp ()
  "Like DAT-DOTW-stamp but with additional space and 12-hour format time."
  (interactive)
  (let (string$)
    (setq string$ (concat (format-time-string "%Y") "-" (upcase (format-time-string "%h")) "-" (format-time-string "%d")))
    (setq string$ (concat string$ " " (upcase (format-time-string "%a"))))
    (setq string$ (concat string$ " " (format-time-string "%l:%M %p")))
    (setq string$ (string-replace "  " " " string$))
    (insert string$)))
; (describe-function 'DAT-DOTW-TM-stamp)


(defun time-stamp ()
  "Time stamp (24-hour format)."
  (interactive)
  (insert (format-time-string "%H:%M")))
; (describe-function 'time-stamp)

(defun TIME-STAMP ()
  "Time stamp (24-hour format)."
  (interactive)
  (insert (format-time-string "%H:%M")))
; (describe-function 'time-stamp)

(defun TM-stamp ()
  "Time stamp (12-hour format)."
  (interactive)
  (let (out$)
    (setq out$ (format-time-string "%l:%M %p"))
    (if (string= (substring out$ 0 1) " ")
      (setq out$ (substring out$ 1 (length out$)))
    )
    (insert out$)
  )
)
; (describe-function 'TM-stamp)

(defun time-stamp-compact ()
  "Time stamp which prints capital English letter for hour and lowercase Greek letter for pentaminute."
  (interactive)
  (let (hour minute minute-2 hour-latin minute-greek debug-1)
    (setq debug-1 nil)
    (setq hour (string-to-number (format-time-string "%H")))
    (DEBUG debug-1 nil (concat "hour = " (number-to-string hour)))
    (setq minute (string-to-number (format-time-string "%M")))
    (DEBUG debug-1 nil (concat "minute = " (number-to-string minute)))
    (setq minute-2 (/ minute 5))
    (cond
      ((eq hour 0) (setq hour-latin "X"))
      ((eq hour 1) (setq hour-latin "A"))
      ((eq hour 2) (setq hour-latin "B"))
      ((eq hour 3) (setq hour-latin "C"))
      ((eq hour 4) (setq hour-latin "D"))
      ((eq hour 5) (setq hour-latin "E"))
      ((eq hour 6) (setq hour-latin "F"))
      ((eq hour 7) (setq hour-latin "G"))
      ((eq hour 8) (setq hour-latin "H"))
      ((eq hour 9) (setq hour-latin "I"))
      ((eq hour 10) (setq hour-latin "J"))
      ((eq hour 11) (setq hour-latin "K"))
      ((eq hour 12) (setq hour-latin "L"))
      ((eq hour 13) (setq hour-latin "M"))
      ((eq hour 14) (setq hour-latin "N"))
      ((eq hour 15) (setq hour-latin "O"))
      ((eq hour 16) (setq hour-latin "P"))
      ((eq hour 17) (setq hour-latin "Q"))
      ((eq hour 18) (setq hour-latin "R"))
      ((eq hour 19) (setq hour-latin "S"))
      ((eq hour 20) (setq hour-latin "T"))
      ((eq hour 21) (setq hour-latin "U"))
      ((eq hour 22) (setq hour-latin "V"))
      ((eq hour 23) (setq hour-latin "W"))
      ((eq hour 24) (setq hour-latin "X")))
    (DEBUG debug-1 nil (concat "hour-latin = " hour-latin))
    (cond
      ((eq minute-2 0) (setq minute-greek "μ"))
      ((eq minute-2 1) (setq minute-greek "α"))
      ((eq minute-2 2) (setq minute-greek "β"))
      ((eq minute-2 3) (setq minute-greek "γ"))
      ((eq minute-2 4) (setq minute-greek "δ"))
      ((eq minute-2 5) (setq minute-greek "ε"))
      ((eq minute-2 6) (setq minute-greek "ζ"))
      ((eq minute-2 7) (setq minute-greek "η"))
      ((eq minute-2 8) (setq minute-greek "θ"))
      ((eq minute-2 9) (setq minute-greek "ι"))
      ((eq minute-2 10) (setq minute-greek "κ"))
      ((eq minute-2 11) (setq minute-greek "λ")))
    (DEBUG debug-1 nil (concat "minute-greek = " minute-greek))
    (insert (concat hour-latin minute-greek))))
; (describe-function 'time-stamp-compact)

(defun date-stamp-compact ()
  "Date-stamp compactified to 4 characters (by means of a base-100 numeral code)."
  (interactive)
  (char-trans-Arabic-pair-2-base-100-1 (format-time-string "%Y%m%d")))
; (describe-function 'date-stamp-compact)

(defun now-stamp ()
  "Stamps compactified date and time."
  (interactive)
  (date-stamp-compact)
  (time-stamp-compact))
					; (describe-function 'now-stamp)

(defun NOW-stamp ()
  "Alias of DAT-DOTW-TM-stamp."
  (DAT-DOTW-TM-stamp))
; (describe-function 'NOW-stamp)

(defun time-stamp-decode (pair$)
  "Decodes any output of time-stamp-compact."
  (interactive "sEnter Latin-Greek pair: ")
  (let (Latin$ greek$ hour$ pentaminute$)
    (setq Latin$ (substring pair$ 0 1))
    (setq greek$ (substring pair$ 1 2))
    (setq hour$ (cond
      ((string= Latin$ "A") "01")
      ((string= Latin$ "B") "02")
      ((string= Latin$ "C") "03")
      ((string= Latin$ "D") "04")
      ((string= Latin$ "E") "05")
      ((string= Latin$ "F") "06")
      ((string= Latin$ "G") "07")
      ((string= Latin$ "H") "08")
      ((string= Latin$ "I") "09")
      ((string= Latin$ "J") "10")
      ((string= Latin$ "K") "11")
      ((string= Latin$ "L") "12")
      ((string= Latin$ "M") "13")
      ((string= Latin$ "N") "14")
      ((string= Latin$ "O") "15")
      ((string= Latin$ "P") "16")
      ((string= Latin$ "Q") "17")
      ((string= Latin$ "R") "18")
      ((string= Latin$ "S") "19")
      ((string= Latin$ "T") "20")
      ((string= Latin$ "U") "21")
      ((string= Latin$ "V") "22")
      ((string= Latin$ "W") "23")
      ((string= Latin$ "X") "00")))
    (setq pentaminute$ (cond
      ((string= greek$ "α") "05")
      ((string= greek$ "β") "10")
      ((string= greek$ "γ") "15")
      ((string= greek$ "δ") "20")
      ((string= greek$ "ε") "25")
      ((string= greek$ "ζ") "30")
      ((string= greek$ "η") "35")
      ((string= greek$ "θ") "40")
      ((string= greek$ "ι") "45")
      ((string= greek$ "κ") "50")
      ((string= greek$ "λ") "55")
      ((string= greek$ "μ") "00")))
    (message (concat hour$ "⬠" pentaminute$))))
; (describe-function 'time-stamp-decode)

(defun date-stamp-decode (fourchar$)
  "Decodes any output of date-stamp-compact."
  (interactive "sEnter four-character string: ")
  (let (year$ month^ month$ day$)
    (setq year$ (concat (base-100-2-Arabic-pair (substring fourchar$ 0 1))
      (base-100-2-Arabic-pair (substring fourchar$ 1 2))))
    (setq month^ (string-to-number (base-100-2-Arabic-pair (substring fourchar$ 2 3))))
    (setq month$ (cond
      ((= month^ 1) "JAN")
      ((= month^ 2) "FEB")
      ((= month^ 3) "MAR")
      ((= month^ 4) "APR")
      ((= month^ 5) "MAY")
      ((= month^ 6) "JUN")
      ((= month^ 7) "JUL")
      ((= month^ 8) "AUG")
      ((= month^ 9) "SEP")
      ((= month^ 10) "OCT")
      ((= month^ 11) "NOV")
      ((= month^ 12) "DEC")))
    (setq day$ (base-100-2-Arabic-pair (substring fourchar$ 3 4)))
    (message (concat year$ "-" month$ "-" day$))))
; (describe-function 'date-stamp-decode)

(defun now-stamp-decode (sixchar$)
  "Decodes any output of now-stamp."
  (interactive "sEnter six character-string: ")
  (let (fourchar$ twochar$ date$ time$ (d_1! t))
    (setq fourchar$ (substring sixchar$ 0 4))
    (setq twochar$ (substring sixchar$ 4 6))
    (setq date$ (date-stamp-decode fourchar$))
    (setq time$ (time-stamp-decode twochar$))
    (message (concat date$ " " time$))))
; (describe-function 'now-stamp-decode)
